configuration:
  working_directory: "~/.var/ytdl-sub-working-directory"
  persist_logs:
    logs_directory: "~/.var/ytdl-sub-logs"

presets:
  Music:
    preset:
      - "YouTube Releases"
      - "Max MP3 Quality"
    ytdl_options:
      postprocessors:
        - key: "FFmpegThumbnailsConvertor"
          format: "jpg"
        - key: "EmbedThumbnail"
      postprocessor_args:
        - "-c:v"
        - "mjpeg"
        - "-qmin"
        - "1"
        - "-qscale:v"
        - "1"
        - "-vf"
        - "crop=min(iw\\,ih):min(iw\\,ih)"
      extractor_args:
        youtube:
          lang:
            - "ja"

    overrides:
      # プレイリストタイトルのうちアルバム名を抽出する
      track_album: >-
        { %regex_sub("^(Album - |アルバム - )", "", playlist_title) }

      album_dir: "{track_album_sanitized}"

      # カバー画像は無効化
      album_cover_path: ""
